#!	C:/Strawberry/perl/bin

#	create_euro_teams.pl 26/06/16

use strict;
use warnings;

use MyJSON qw(write_json);
use MyLib qw(sort_HoA);

my $path = 'C:/Mine/perl/Football/data/Euro/';
my $json_file = $path.'teams.json';

my $leagues = {
	"German 1" => [
		"Bayern Munich",
		"Leverkusen",
		"Hamburg",
		"Augsburg",
		"Hertha",
		"Stuttgart",
		"Hoffenheim",
		"Werder Bremen",
		"Mainz",
		"Hannover",
		"Schalke 04",
		"RB Leipzig",
		"Wolfsburg",
		"Dortmund",
		"Freiburg",
		"Ein Frankfurt",
		"M'gladbach",
		"FC Koln",
	],
	"German 2" => [
		"Bochum",
		"Bielefeld",
		"Darmstadt",
		"Ingolstadt",
		"Dresden",
		"Holstein Kiel",
		"Nurnberg",
		"Fortuna Dusseldorf",
		"St Pauli",
		"Regensburg",
		"Greuther Furth",
		"Union Berlin",
		"Duisburg",
		"Sandhausen",
		"Kaiserslautern",
		"Braunschweig",
		"Heidenheim",
		"Erzgebirge Aue",
	],
	"Italian 1" => [
		"Juventus",
		"Cagliari",
		"Verona",
		"Napoli",
		"Atalanta",
		"Roma",
		"Bologna",
		"Torino",
		"Crotone",
		"Milan",
		"Inter",
		"Fiorentina",
		"Lazio",
		"Spal",
		"Sampdoria",
		"Benevento",
		"Sassuolo",
		"Genoa",
		"Udinese",
		"Chievo",
	],
	"Spanish 1" => [
		"Leganes",
		"Alaves",
		"Valencia",
		"Las Palmas",
		"Celta",
		"Sociedad",
		"Girona",
		"Ath Madrid",
		"Sevilla",
		"Espanol",
		"Ath Bilbao",
		"Getafe",
		"Barcelona",
		"Betis",
		"La Coruna",
		"Real Madrid",
		"Levante",
		"Villarreal",
		"Malaga",
		"Eibar",
	],
	"Belgian 1" => [
		"Antwerp",
		"Anderlecht",
		"Charleroi",
		"Kortrijk",
		"Eupen",
		"Waregem",
		"Genk",
		"Waasland-Beveren",
		"Lokeren",
		"Club Brugge",
		"Mechelen",
		"Standard",
		"Oostende",
		"Mouscron",
		"St Truiden",
		"Gent",
	],
	"Welsh" => [
		"Bala Town",
		"Bangor City",
		"Prestatyn",
		"Cefn Druids",
		"Llandudno",
		"Barry Town",
		"Newtown",
		"TNS",
		"Connahs Quay",
		"Cardiff MU",
		"Carmarthen Town",
		"Aberystwyth",
	],
	"N Irish" => [
		"Ballymena",
		"Ballinamallard",
		"Cliftonville",
		"Dungannon",
		"Linfield",
		"Warrenpoint",
		"Crusaders",
		"Glentoran",
		"Ards",
		"Coleraine",
		"Carrick Rangers",
		"Glenavon",
	],
};

my $sorted = sort_HoA ($leagues);
write_json ($json_file, $sorted);
