my $leagues = {
    'Premier League' => [
        'Arsenal',
        'Aston Villa',
        'Bournemouth',
        'Brighton',
        'Burnley',
        'Chelsea',
        'Crystal Palace',
        'Everton',
        'Leicester',
        'Liverpool',
        'Man City',
        'Man United',
        'Newcastle',
        'Norwich',
        'Sheffield United',
        'Southampton',
        'Tottenham',
        'Watford',
        'West Ham',
        'Wolves',
        ],
    'Championship' => [
        'Barnsley',
        'Birmingham',
        'Blackburn',
        'Brentford',
        'Bristol City',
        'Cardiff',
        'Charlton',
        'Derby',
        'Fulham',
        'Huddersfield',
        'Hull',
        'Leeds',
        'Luton',
        'Middlesbrough',
        'Millwall',
        'Nott'm Forest',
        'Preston',
        'QPR',
        'Reading',
        'Sheffield Weds',
        'Stoke',
        'Swansea',
        'West Brom',
        'Wigan',
        ],
    'League One' => [
        'AFC Wimbledon',
        'Accrington',
        'Blackpool',
        'Bolton',
        'Bristol Rvs',
        'Burton',
        'Bury',
        'Coventry',
        'Doncaster',
        'Fleetwood Town',
        'Gillingham',
        'Ipswich',
        'Lincoln',
        'Milton Keynes Dons',
        'Oxford',
        'Peterboro',
        'Portsmouth',
        'Rochdale',
        'Rotherham',
        'Shrewsbury',
        'Southend',
        'Sunderland',
        'Tranmere',
        'Wycombe',
        ],
    'League Two' => [
        'Bradford',
        'Cambridge',
        'Carlisle',
        'Cheltenham',
        'Colchester',
        'Crawley Town',
        'Crewe',
        'Exeter',
        'Forest Green',
        'Grimsby',
        'Leyton Orient',
        'Macclesfield',
        'Mansfield',
        'Morecambe',
        'Newport County',
        'Northampton',
        'Oldham',
        'Plymouth',
        'Port Vale',
        'Salford',
        'Scunthorpe',
        'Stevenage',
        'Swindon',
        'Walsall',
        ],
    'Conference' => [
        'Aldershot',
        'Barnet',
        'Barrow',
        'Boreham Wood',
        'Bromley',
        'Chesterfield',
        'Chorley',
        'Dag and Red',
        'Dover Athletic',
        'Eastleigh',
        'Ebbsfleet',
        'Fylde',
        'Halifax',
        'Harrogate',
        'Hartlepool',
        'Maidenhead',
        'Notts County',
        'Solihull',
        'Stockport',
        'Sutton',
        'Torquay',
        'Woking',
        'Wrexham',
        'Yeovil',
        ],
    'Scots Premier' => [
        'Aberdeen',
        'Celtic',
        'Hamilton',
        'Hearts',
        'Hibernian',
        'Kilmarnock',
        'Livingston',
        'Motherwell',
        'Rangers',
        'Ross County',
        'St Johnstone',
        'St Mirren',
        ],
    'Scots Championship' => [
        'Alloa',
        'Arbroath',
        'Ayr',
        'Dundee',
        'Dundee United',
        'Dunfermline',
        'Inverness C',
        'Morton',
        'Partick',
        'Queen of Sth',
        ],
    'Scots League One' => [
        'Airdrie Utd',
        'Clyde',
        'Dumbarton',
        'East Fife',
        'Falkirk',
        'Forfar',
        'Montrose',
        'Peterhead',
        'Raith Rvs',
        'Stranraer',
        ],
    'Scots League Two' => [
        'Albion Rvs',
        'Annan Athletic',
        'Brechin',
        'Cove Rangers',
        'Cowdenbeath',
        'Edinburgh City',
        'Elgin',
        'Queens Park',
        'Stenhousemuir',
        'Stirling',
        ],
};
